# Generated by Django 4.2.5 on 2024-05-19 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("booking_confirmed", "booking_confirmed"),
                            ("booking_cancelled", "booking_cancelled"),
                            ("booking_inquiry", "booking_inquiry"),
                            ("review", "review"),
                            ("payment_method", "payment_method"),
                            ("user_verification", "user_verification"),
                            ("payout", "payout"),
                            ("sign_up", "sign_up"),
                        ],
                        max_length=30,
                    ),
                ),
                ("data", models.JSONField()),
                ("is_read", models.BooleanField(default=False)),
                (
                    "n_type",
                    models.CharField(
                        choices=[
                            ("admin_notification", "admin_notification"),
                            ("user_notification", "user_notification"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
