# Generated by Django 4.2.5 on 2024-05-19 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HostPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("invoice_no", models.CharField(max_length=200, unique=True)),
                ("total_amount", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unpaid", "unpaid"),
                            ("paid", "paid"),
                            ("failed", "failed"),
                        ],
                        default="unpaid",
                        max_length=15,
                    ),
                ),
                ("payment_date", models.DateField()),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Host Payment",
                "verbose_name_plural": "2. Host Payment",
            },
        ),
        migrations.CreateModel(
            name="OnlinePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transaction_number", models.CharField(max_length=200, unique=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("ssl_commerz", "ssl_commerz")], max_length=15
                    ),
                ),
                ("amount", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "initiated"),
                            ("completed", "completed"),
                            ("cancelled", "cancelled"),
                            ("rejected", "rejected"),
                            ("failed", "failed"),
                            ("paid", "paid"),
                        ],
                        max_length=15,
                    ),
                ),
                ("meta", models.JSONField(default=dict)),
                ("has_hit_ipn", models.BooleanField(default=False)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bookings.booking",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Online Payment",
                "verbose_name_plural": "1. Online Payment",
            },
        ),
        migrations.CreateModel(
            name="HostPayMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "m_type",
                    models.CharField(
                        choices=[
                            ("bkash", "bkash"),
                            ("nagad", "nagad"),
                            ("rocket", "rocket"),
                            ("bank", "bank"),
                        ],
                        max_length=20,
                    ),
                ),
                ("account_no", models.CharField(max_length=30, unique=True)),
                ("account_name", models.CharField(max_length=150)),
                ("bank_name", models.CharField(blank=True, max_length=150)),
                ("branch_name", models.CharField(blank=True, max_length=150)),
                ("routing_number", models.CharField(blank=True, max_length=30)),
                ("is_default", models.BooleanField()),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Host PayMethod",
                "verbose_name_plural": "1. Host PayMethod",
            },
        ),
        migrations.CreateModel(
            name="HostPaymentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("invoice_no", models.CharField(max_length=200)),
                ("reservation_code", models.CharField(max_length=200)),
                ("night_count", models.PositiveIntegerField()),
                ("guest_count", models.PositiveIntegerField()),
                ("amount", models.FloatField()),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="bookings.booking",
                    ),
                ),
                (
                    "host_payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payments.hostpayment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Host Payment Item",
                "verbose_name_plural": "2. Host Payment Item",
            },
        ),
        migrations.AddField(
            model_name="hostpayment",
            name="pay_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="payments.hostpaymethod"
            ),
        ),
    ]
