# Generated by Django 4.2.5 on 2024-07-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listingcalendar",
            name="note",
            field=models.TextField(blank=True),
        ),
    ]
