# Generated by Django 4.2.5 on 2024-05-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CancellationPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("refund_percentage", models.FloatField(default=0)),
                ("cancellation_deadline", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Cancellation Policy",
                "verbose_name_plural": "1. Cancellation Policy",
            },
        ),
        migrations.CreateModel(
            name="ServiceCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                (
                    "sc_type",
                    models.CharField(
                        choices=[
                            ("host_charge", "host_charge"),
                            ("guest_charge", "guest_charge"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "calculation_type",
                    models.CharField(
                        choices=[("flat", "flat"), ("percentage", "percentage")],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Charge",
                "verbose_name_plural": "2. Service Charge",
            },
        ),
        migrations.CreateModel(
            name="ServiceChargeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
                (
                    "sc_type",
                    models.CharField(
                        choices=[
                            ("host_charge", "host_charge"),
                            ("guest_charge", "guest_charge"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "calculation_type",
                    models.CharField(
                        choices=[("flat", "flat"), ("percentage", "percentage")],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Service Charge History",
                "verbose_name_plural": "2. Service Charge History",
            },
        ),
    ]
