# Generated by Django 4.2.5 on 2024-05-19 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("invoice_no", models.CharField(max_length=200, unique=True)),
                (
                    "pgw_transaction_number",
                    models.CharField(blank=True, max_length=200),
                ),
                ("reservation_code", models.CharField(blank=True, max_length=200)),
                ("check_in", models.DateField()),
                ("check_out", models.DateField()),
                ("night_count", models.PositiveIntegerField()),
                ("children_count", models.PositiveIntegerField()),
                ("infant_count", models.PositiveIntegerField()),
                ("adult_count", models.PositiveIntegerField()),
                ("guest_count", models.PositiveIntegerField()),
                ("price", models.FloatField()),
                ("guest_service_charge", models.FloatField()),
                ("total_price", models.FloatField()),
                ("paid_amount", models.FloatField(default=0)),
                ("host_service_charge", models.FloatField()),
                ("host_pay_out", models.FloatField()),
                ("total_profit", models.FloatField()),
                ("gateway_fee", models.FloatField(default=0)),
                ("refund_amount", models.FloatField(default=0)),
                ("is_refunded", models.BooleanField(default=False)),
                ("price_info", models.JSONField()),
                (
                    "guest_payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "unpaid"),
                            ("paid", "paid"),
                            ("failed", "failed"),
                        ],
                        default="unpaid",
                        max_length=15,
                    ),
                ),
                (
                    "host_payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "unpaid"),
                            ("paid", "paid"),
                            ("failed", "failed"),
                        ],
                        default="unpaid",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "initiated"),
                            ("confirmed", "confirmed"),
                            ("cancelled", "cancelled"),
                        ],
                        default="initiated",
                        max_length=15,
                    ),
                ),
                ("cancellation_reason", models.TextField(blank=True)),
                ("host_review_done", models.BooleanField(default=False)),
                ("guest_review_done", models.BooleanField(default=False)),
                ("calendar_info", models.JSONField(default=dict)),
                ("chat_room_id", models.CharField(blank=True, max_length=200)),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guest_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="host_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "1. Booking",
            },
        ),
        migrations.CreateModel(
            name="ListingBookingReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_host_review", models.BooleanField(default=False)),
                ("is_guest_review", models.BooleanField(default=False)),
                ("rating", models.PositiveIntegerField()),
                ("review", models.TextField()),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookings.booking",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="listings.listing",
                    ),
                ),
                (
                    "review_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_for_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Review",
                "verbose_name_plural": "2. Booking Review",
            },
        ),
    ]
